name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['master']

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install
        run: pnpm install
      - name: Run Prettier
        run: pnpm format
      - name: Run cargo fmt
        working-directory: src-tauri
        run: cargo fmt
      - name: Check output
        run: git --no-pager diff --exit-code HEAD

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install Linux dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y \
            build-essential \
            curl \
            file \
            libayatana-appindicator3-dev \
            libgtk-3-dev \
            librsvg2-dev \
            libssl-dev \
            libwebkit2gtk-4.0-dev \
            wget
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm tauri build
